# adservice
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  namespace: webapps
spec:
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9555"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
        - name: server
          image: 483898563284.dkr.ecr.ap-south-1.amazonaws.com/webapps/microservice:adservice-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9555
          env:
            - name: PORT
              value: "9555"
          resources:
            requests:
              cpu: 200m
              memory: 180Mi
            limits:
              cpu: 300m
              memory: 300Mi
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:9555"]
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:9555"]
---
apiVersion: v1
kind: Service
metadata:
  name: adservice
  namespace: webapps
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9555"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app: adservice
  ports:
    - name: grpc
      port: 9555
      targetPort: 9555
